// 037–040: 생성 타입과 OperationMap만 노출한다. 어떤 앱도 아직 이 패키지를 import하지 않는다.
// HTTP/WebSocket Adapter는 4단계(Desktop 전환)에서 추가된다.
export type * from "./generated/workbench";
export type {
  AgentDescriptor,
  AgentExchange,
  AgentPanelEndpoint,
  AgentRun,
  AgentRunRequest,
  AgentRunSettings,
  AgentToolCandidateResponse,
  AgentWorkspaceSyncResponse,
  BenchCloseOutput,
  BenchOpenInput,
  BenchOpenOutput,
  BenchTitleRequested,
  Call,
  CallReply,
  CallReplyByOperation,
  CallRequest,
  DescribeOutput,
  EventBySchema,
  EventEnvelope,
  EventFrame,
  EventItem,
  EventMap,
  EventSchemaId,
  ExchangeRequested,
  FaultCode,
  GapNotice,
  GapReason,
  GitBranch,
  GitCommitDetail,
  GitCommitGraph,
  GitCommitHistory,
  GitFileDiff,
  GitRemote,
  GitWorktree,
  GitWorktreeChanges,
  Goal,
  GoalStatus,
  OperationDescriptor,
  OperationId,
  OperationMap,
  OrchestrationWorkspaceUpdated,
  Outcome,
  Project,
  ProjectCreateInput,
  ProviderSession,
  RunEvent,
  SavedPrompt,
  Schemas,
  StreamCursor,
  TitleChangeResult,
  WorkbenchFault,
  WorktreeChange,
  WorktreeChanged,
  WorktreeFileEntry,
  WorktreeTextFile,
} from "./operation-map";
export { CALLS_PATH, PROTOCOL_VERSION } from "./operation-map";
