// operation 종류(043): 조회는 멱등성 키 없이 보내고 응답을 잃으면 새 요청으로 다시 보낸다. 변경은 키를 붙이고 같은 세대에서만
// 같은 키로 재시도한다. 정본은 protocol `operations::spec_for(op).kind`다 — 이 표는 `system.describe`에서 뽑았고,
// `Record<OperationId, …>`라 새 operation이 빠지면 타입 검사가 실패하며, 통합 시험이 실제 서버의 describe와 대조한다.
import type { OperationId } from "./operation-map";

export type OperationKind = "query" | "command";

export const OPERATION_KINDS: Record<OperationId, OperationKind> = {
  "agent.list": "query",
  "agent.listProviderSessions": "query",
  "agentRunSettings.get": "query",
  "agentRunSettings.save": "command",
  "bench.close": "command",
  "bench.open": "command",
  "bench.requestTitle": "command",
  "exchange.acknowledge": "command",
  "exchange.getForRun": "query",
  "exchange.list": "query",
  "exchange.listPeers": "query",
  "exchange.send": "command",
  "exchange.sendFromRun": "command",
  "exchange.syncWorkspace": "command",
  "git.createWorktree": "command",
  "git.deleteWorktree": "command",
  "git.listBranches": "query",
  "git.listRemotes": "query",
  "git.listWorktrees": "query",
  "goal.clear": "command",
  "goal.create": "command",
  "goal.get": "query",
  "goal.recordProgress": "command",
  "goal.update": "command",
  "orchestration.adoptManualChild": "command",
  "orchestration.assignChildTask": "command",
  "orchestration.bindCoordinator": "command",
  "orchestration.bootstrap": "command",
  "orchestration.cancelChildTask": "command",
  "orchestration.cancelTask": "command",
  "orchestration.collectChildResults": "command",
  "orchestration.collectReports": "query",
  "orchestration.createChildTask": "command",
  "orchestration.delegateGoal": "command",
  "orchestration.dispatchPrompt": "command",
  "orchestration.get": "query",
  "orchestration.getAgentRole": "query",
  "orchestration.getOwnTask": "query",
  "orchestration.handoffCoordinator": "command",
  "orchestration.interruptChildTask": "command",
  "orchestration.listChildTasks": "query",
  "orchestration.listRecoverable": "query",
  "orchestration.listTasks": "query",
  "orchestration.reassignChildTask": "command",
  "orchestration.reassignTask": "command",
  "orchestration.recover": "command",
  "orchestration.reportBlocked": "command",
  "orchestration.reportProgress": "command",
  "orchestration.reportResult": "command",
  "orchestration.requestParentInput": "command",
  "orchestration.respondInput": "command",
  "orchestration.retryChildTask": "command",
  "orchestration.retryTask": "command",
  "orchestration.sendChildCommand": "command",
  "orchestration.sendChildMessage": "command",
  "orchestration.sendParentMessage": "command",
  "orchestration.setPresentation": "command",
  "orchestration.waitChildTasks": "query",
  "project.create": "command",
  "project.delete": "command",
  "project.list": "query",
  "project.update": "command",
  "run.cancel": "command",
  "run.cancelAndSend": "command",
  "run.listToolCandidates": "query",
  "run.replay": "query",
  "run.respondPermission": "command",
  "run.sendPrompt": "command",
  "run.setPermissionMode": "command",
  "run.start": "command",
  "run.steer": "command",
  "savedPrompt.create": "command",
  "savedPrompt.delete": "command",
  "savedPrompt.list": "query",
  "savedPrompt.update": "command",
  "system.describe": "query",
  "worktree.getChanges": "query",
  "worktree.getCommitDetail": "query",
  "worktree.getCommitFileDiff": "query",
  "worktree.getFileDiff": "query",
  "worktree.getGraph": "query",
  "worktree.listChanges": "query",
  "worktree.listFiles": "query",
  "worktree.listHistory": "query",
  "worktree.readTextFile": "query",
};

export function isQueryOperation(operation: OperationId): boolean {
  return OPERATION_KINDS[operation] === "query";
}
